-- MySQL Script generated by MySQL Workbench
-- Fri Apr 30 12:58:35 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mediscreen
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mediscreen
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mediscreen` DEFAULT CHARACTER SET utf8 ;
USE `mediscreen` ;

-- -----------------------------------------------------
-- Table `mediscreen`.`patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mediscreen`.`patient` ;

CREATE TABLE IF NOT EXISTS `mediscreen`.`patient` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `familly_name` VARCHAR(60) NOT NULL,
  `given_name` VARCHAR(60) NOT NULL,
  `date_of_birth` DATETIME NOT NULL,
  `gender` CHAR(1) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `phone_number` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
